package com.ramaj.wtsappcleaner;

import android.content.*;import java.io.*;import java.util.*;import java.util.concurrent.atomic.AtomicBoolean;

final class CleanerEngine {
 interface Listener{void progress(Models.Progress p);}
 private final Context ctx;private final DatabaseHelper db;private final AtomicBoolean stop;private final Listener listener;private final android.content.SharedPreferences prefs;private long exact=0,visual=0,possible=0,recovered=0,startMs;
 CleanerEngine(Context c,DatabaseHelper d,AtomicBoolean s,Listener l){ctx=c;db=d;stop=s;listener=l;prefs=c.getSharedPreferences("settings",0);}
 void run(boolean deep)throws Exception{startMs=System.currentTimeMillis();long run=startMs;ArrayList<Models.FileEntry> files=discover(run);if(stopped())return;exact(files);if(stopped())return;imageVisual(files);if(stopped())return;if(deep)videoVisual(files);emit("Finishing",100,files.size(),files.size(),"Scan complete");}
 private ArrayList<Models.FileEntry> discover(long run){ArrayList<Models.FileEntry> out=new ArrayList<>();ArrayList<File> roots=new ArrayList<>();addRoot(roots,"/storage/emulated/0/Android/media/com.whatsapp/WhatsApp/Media");addRoot(roots,"/storage/emulated/0/WhatsApp/Media");if(prefs.getBoolean("business",true)){addRoot(roots,"/storage/emulated/0/Android/media/com.whatsapp.w4b/WhatsApp Business/Media");addRoot(roots,"/storage/emulated/0/WhatsApp Business/Media");}File sr=new File("/storage");File[] vols=sr.listFiles();if(vols!=null)for(File v:vols)if(v.isDirectory()&&v.getName().contains("-")){addRoot(roots,new File(v,"Android/media/com.whatsapp/WhatsApp/Media").getAbsolutePath());addRoot(roots,new File(v,"WhatsApp/Media").getAbsolutePath());}
  long est=36000;for(File r:roots)walk(r,out,run,est);emit("Index ready",10,out.size(),out.size(),out.size()+" files found");return out;}
 private void addRoot(List<File> a,String p){File f=new File(p);if(f.isDirectory())a.add(f);}
 private void walk(File d,List<Models.FileEntry> out,long run,long est){if(stopped())return;File[] aa=d.listFiles();if(aa==null)return;for(File f:aa){if(stopped())return;if(f.isDirectory()){String n=f.getName();if(n.equals(".Statuses")||n.equals("Statuses")||n.equals(".thumbnails")||n.equals("thumbnails"))continue;walk(f,out,run,est);}else if(f.isFile()&&!f.getName().equals(".nomedia")){boolean sent=f.getAbsolutePath().contains("/Sent/");if(sent&&!prefs.getBoolean("sent",true))continue;Models.FileEntry e=new Models.FileEntry(f.getAbsolutePath(),f.length(),f.lastModified(),category(f.getName()),sent);out.add(e);db.upsert(e,run);if(out.size()%250==0)emit("Finding WhatsApp files",Math.min(9,(int)(out.size()*9/est)),out.size(),est,"Scanning folders");}}}

 private void exact(List<Models.FileEntry> files)throws Exception{Map<Long,List<Models.FileEntry>> sizes=new HashMap<>();for(Models.FileEntry f:files)if(f.size>0)sizes.computeIfAbsent(f.size,k->new ArrayList<>()).add(f);ArrayList<Models.FileEntry> rep=new ArrayList<>();for(List<Models.FileEntry> g:sizes.values())if(g.size()>1)rep.addAll(g);long n=rep.size(),i=0;Map<String,List<Models.FileEntry>> quick=new HashMap<>();for(Models.FileEntry f:rep){if(stopped())return;i++;String q=db.getString(f.path,"quick");if(q==null){try{q=Hasher.quickHash(f.path,f.size);db.putString(f.path,"quick",q);}catch(Exception ignored){}}if(q!=null)quick.computeIfAbsent(f.size+":"+q,k->new ArrayList<>()).add(f);if(i%20==0)emit("Fast duplicate filter",10+(int)(i*15/Math.max(1,n)),i,n,"Reading small fingerprints");}
  ArrayList<Models.FileEntry> fullCand=new ArrayList<>();for(List<Models.FileEntry> g:quick.values())if(g.size()>1)fullCand.addAll(g);n=fullCand.size();i=0;Map<String,List<Models.FileEntry>> full=new HashMap<>();for(Models.FileEntry f:fullCand){if(stopped())return;i++;String h=db.getString(f.path,"full");if(h==null){try{h=Hasher.sha256(f.path,this::stopped);db.putString(f.path,"full",h);}catch(InterruptedException x){return;}catch(Exception ignored){}}if(h!=null)full.computeIfAbsent(f.size+":"+h,k->new ArrayList<>()).add(f);if(i%5==0)emit("Confirming exact copies",25+(int)(i*20/Math.max(1,n)),i,n,"Full SHA-256 verification");}
  boolean auto=prefs.getBoolean("autoExact",true);for(List<Models.FileEntry> g:full.values())if(g.size()>1){Models.FileEntry keep=best(g);for(Models.FileEntry d:g)if(d!=keep&&!db.hasDup(d.path)){db.addDup(keep.path,d.path,"EXACT",100,d.category,d.size);exact++;if(auto){try{File dst=MoveManager.move(ctx,d.path,d.category,"EXACT");db.markMoved(d.path);db.addMove(d.path,dst.getAbsolutePath(),"EXACT",d.size);recovered+=d.size;}catch(Exception ignored){}}emit("Saving confirmed duplicates",45,exact,Math.max(exact,1),new File(d.path).getName());}}}

 private void imageVisual(List<Models.FileEntry> files){ArrayList<Models.FileEntry> imgs=new ArrayList<>();for(Models.FileEntry f:files)if(f.category.equals("Images")&&new File(f.path).exists())imgs.add(f);int total=imgs.size(),idx=0;Map<Integer,List<Models.ImageSig>> buckets=new HashMap<>();HashSet<String> pair=new HashSet<>();int sensitivity=prefs.getInt("sensitivity",1);int high=sensitivity==0?6:sensitivity==1?8:10,poss=high+4;for(Models.FileEntry f:imgs){if(stopped())return;idx++;Models.ImageSig s;Long ph=db.getLong(f.path,"phash");if(ph!=null){Long w=db.getLong(f.path,"width"),h=db.getLong(f.path,"height");s=new Models.ImageSig(f,ph,w==null?0:w.intValue(),h==null?0:h.intValue());}else{s=Hasher.imageSig(f);if(s!=null)db.putImage(f.path,s.hash,s.width,s.height);}if(s==null)continue;HashSet<Models.ImageSig> cand=new HashSet<>();for(int band=0;band<8;band++){int bv=(int)((s.hash>>>(band*8))&255L);List<Models.ImageSig> l=buckets.get((band<<8)|bv);if(l!=null)cand.addAll(l);}for(Models.ImageSig o:cand){if(stopped())return;String pk=o.f.path.compareTo(s.f.path)<0?o.f.path+"|"+s.f.path:s.f.path+"|"+o.f.path;if(!pair.add(pk))continue;int hd=Hasher.ham(s.hash,o.hash);double ar=aspectDiff(s.width,s.height,o.width,o.height);if(hd<=poss&&ar<=0.08){Models.FileEntry keep=betterVisual(s.f,s.width,s.height,o.f,o.width,o.height);Models.FileEntry dup=keep==s.f?o.f:s.f;if(db.hasDup(dup.path))continue;int conf=hd<=high&&ar<=0.04?Math.max(91,99-hd):Math.max(78,90-hd);String kind=conf>=91?"VISUAL":"POSSIBLE";db.addDup(keep.path,dup.path,kind,conf,dup.category,dup.size);if(kind.equals("VISUAL"))visual++;else possible++;}}
   for(int band=0;band<8;band++){int bv=(int)((s.hash>>>(band*8))&255L);buckets.computeIfAbsent((band<<8)|bv,k->new ArrayList<>()).add(s);}if(idx%10==0)emit("Matching similar photos",45+(int)(idx*35L/Math.max(1,total)),idx,total,"Real pixel pHash • "+visual+" visual matches");}}

 private void videoVisual(List<Models.FileEntry> files){ArrayList<Models.FileEntry> vids=new ArrayList<>();for(Models.FileEntry f:files)if(f.category.equals("Videos")&&new File(f.path).exists())vids.add(f);int total=vids.size(),idx=0;Map<Integer,List<Models.VideoSig>> buckets=new HashMap<>();HashSet<String> pair=new HashSet<>();for(Models.FileEntry f:vids){if(stopped())return;idx++;Models.VideoSig s=null;Long d=db.getLong(f.path,"duration"),v1=db.getLong(f.path,"v1"),v2=db.getLong(f.path,"v2"),v3=db.getLong(f.path,"v3"),w=db.getLong(f.path,"width"),h=db.getLong(f.path,"height");if(d!=null&&v1!=null&&v2!=null&&v3!=null)s=new Models.VideoSig(f,v1,v2,v3,d,w==null?0:w.intValue(),h==null?0:h.intValue());else{s=Hasher.videoSig(f);if(s!=null)db.putVideo(f.path,s);}if(s==null)continue;int durBucket=(int)(s.duration/3000);HashSet<Models.VideoSig> cand=new HashSet<>();for(int dbu=durBucket-1;dbu<=durBucket+1;dbu++)for(int band=0;band<8;band++){int bv=(int)((s.h2>>>(band*8))&255L);List<Models.VideoSig> l=buckets.get((dbu<<16)|(band<<8)|bv);if(l!=null)cand.addAll(l);}for(Models.VideoSig o:cand){String pk=o.f.path.compareTo(s.f.path)<0?o.f.path+"|"+s.f.path:s.f.path+"|"+o.f.path;if(!pair.add(pk))continue;long dd=Math.abs(s.duration-o.duration);if(dd>Math.max(3500,Math.max(s.duration,o.duration)/20))continue;int a=Hasher.ham(s.h1,o.h1),b=Hasher.ham(s.h2,o.h2),c=Hasher.ham(s.h3,o.h3),avg=(a+b+c)/3;double ar=aspectDiff(s.width,s.height,o.width,o.height);if(avg<=11&&ar<=.08){Models.FileEntry keep=betterVisual(s.f,s.width,s.height,o.f,o.width,o.height);Models.FileEntry dup=keep==s.f?o.f:s.f;if(db.hasDup(dup.path))continue;int conf=avg<=7&&ar<=.04?Math.max(92,99-avg):Math.max(80,91-avg);String kind=conf>=92?"VISUAL":"POSSIBLE";db.addDup(keep.path,dup.path,kind,conf,dup.category,dup.size);if(kind.equals("VISUAL"))visual++;else possible++;}}
   for(int band=0;band<8;band++){int bv=(int)((s.h2>>>(band*8))&255L);buckets.computeIfAbsent((durBucket<<16)|(band<<8)|bv,k->new ArrayList<>()).add(s);}if(idx%2==0)emit("Matching similar videos",80+(int)(idx*17L/Math.max(1,total)),idx,total,"3-frame native video fingerprints");}}

 private Models.FileEntry best(List<Models.FileEntry> g){Models.FileEntry b=g.get(0);for(Models.FileEntry f:g)if((b.sent&&!f.sent)||((b.sent==f.sent)&&f.mtime<b.mtime))b=f;return b;}
 private Models.FileEntry betterVisual(Models.FileEntry a,int aw,int ah,Models.FileEntry b,int bw,int bh){if(a.sent!=b.sent)return a.sent?b:a;long ap=(long)aw*ah,bp=(long)bw*bh;if(ap!=bp)return ap>bp?a:b;if(a.size!=b.size)return a.size>b.size?a:b;return a.mtime<=b.mtime?a:b;}
 private double aspectDiff(int w1,int h1,int w2,int h2){if(w1<=0||h1<=0||w2<=0||h2<=0)return 0;double a=w1/(double)h1,b=w2/(double)h2;return Math.abs(a-b)/Math.max(a,b);}
 private boolean stopped(){return stop.get();}
 private void emit(String phase,int pct,long cur,long tot,String detail){Models.Progress p=new Models.Progress();p.phase=phase;p.percent=Math.max(0,Math.min(100,pct));p.current=cur;p.total=tot;p.detail=detail;p.exact=exact;p.visual=visual;p.possible=possible;p.recovered=recovered;long el=Math.max(1,System.currentTimeMillis()-startMs);p.rate=cur*1000.0/el;p.etaSec=p.rate>0&&tot>cur?(long)((tot-cur)/p.rate):0;listener.progress(p);}
 static String category(String n){int dot=n.lastIndexOf('.');String e=dot<0?"":n.substring(dot+1).toLowerCase(Locale.ROOT);if(Arrays.asList("jpg","jpeg","png","webp","gif","bmp","heic","heif","tif","tiff","avif").contains(e))return "Images";if(Arrays.asList("mp4","mkv","avi","mov","3gp","webm","m4v","mpeg","mpg","mts","m2ts","ts").contains(e))return "Videos";if(Arrays.asList("mp3","aac","m4a","ogg","opus","wav","amr","flac","wma","mid","midi").contains(e))return "Audio";if(e.equals("pdf"))return "PDF";if(Arrays.asList("xlsx","xls","xlsm","xlsb","csv","ods","tsv").contains(e))return "Excel";if(Arrays.asList("doc","docx","odt","rtf").contains(e))return "Word";if(Arrays.asList("ppt","pptx","odp","pps","ppsx").contains(e))return "PowerPoint";if(Arrays.asList("zip","rar","7z","tar","gz","bz2","xz","tgz","cab","iso").contains(e))return "Archives";if(Arrays.asList("vcf","vcard").contains(e))return "Contacts";if(Arrays.asList("apk","xapk","apks","aab").contains(e))return "APK";return "Other";}
}
