package com.ramaj.wtsappcleaner;

import android.app.*;import android.content.*;import android.os.*;import java.util.concurrent.atomic.AtomicBoolean;

public class CleanerService extends Service {
 public static final String ACT_START="com.ramaj.wtsappcleaner.START",ACT_STOP="com.ramaj.wtsappcleaner.STOP",BROADCAST="com.ramaj.wtsappcleaner.PROGRESS";private static final String CH="cleaner_progress";private final AtomicBoolean stop=new AtomicBoolean(false);private Thread worker;private long lastNotif=0;
 public void onCreate(){super.onCreate();NotificationManager nm=getSystemService(NotificationManager.class);NotificationChannel c=new NotificationChannel(CH,"Cleaner progress",NotificationManager.IMPORTANCE_LOW);c.setSound(null,null);c.enableVibration(false);nm.createNotificationChannel(c);}
 public int onStartCommand(Intent in,int flags,int id){String a=in==null?null:in.getAction();if(ACT_STOP.equals(a)){stop.set(true);stopSelf();return START_NOT_STICKY;}if(worker!=null&&worker.isAlive())return START_STICKY;boolean deep=in!=null&&in.getBooleanExtra("deep",false);stop.set(false);startForeground(77,notification("Starting",0,"Preparing scan"));worker=new Thread(()->{DatabaseHelper db=new DatabaseHelper(this);try{new CleanerEngine(this,db,stop,p->publish(p)).run(deep);}catch(Throwable e){Models.Progress p=new Models.Progress();p.phase="Error";p.detail=e.getClass().getSimpleName()+": "+e.getMessage();publish(p);}finally{stopForeground(false);stopSelf();}},"RamajCleaner");worker.start();return START_STICKY;}
 private void publish(Models.Progress p){Intent b=new Intent(BROADCAST).setPackage(getPackageName());b.putExtra("phase",p.phase);b.putExtra("detail",p.detail);b.putExtra("percent",p.percent);b.putExtra("current",p.current);b.putExtra("total",p.total);b.putExtra("exact",p.exact);b.putExtra("visual",p.visual);b.putExtra("possible",p.possible);b.putExtra("recovered",p.recovered);b.putExtra("rate",p.rate);b.putExtra("eta",p.etaSec);sendBroadcast(b);getSharedPreferences("live",0).edit().putString("phase",p.phase).putString("detail",p.detail).putInt("percent",p.percent).putLong("current",p.current).putLong("total",p.total).putLong("exact",p.exact).putLong("visual",p.visual).putLong("possible",p.possible).putLong("recovered",p.recovered).apply();long now=System.currentTimeMillis();if(now-lastNotif>5000||p.percent==100){getSystemService(NotificationManager.class).notify(77,notification(p.phase,p.percent,p.current+"/"+p.total+" • Exact "+p.exact+" • Similar "+p.visual));lastNotif=now;}}
 private Notification notification(String title,int pct,String line){Intent i=new Intent(this,MainActivity.class);PendingIntent pi=PendingIntent.getActivity(this,0,i,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);Intent si=new Intent(this,CleanerService.class).setAction(ACT_STOP);PendingIntent sp=PendingIntent.getService(this,1,si,PendingIntent.FLAG_IMMUTABLE|PendingIntent.FLAG_UPDATE_CURRENT);return new Notification.Builder(this,CH).setSmallIcon(android.R.drawable.ic_menu_search).setContentTitle("Ramaj Wtsapp Cleaner • "+pct+"%").setContentText(title+" • "+line).setProgress(100,pct,false).setOnlyAlertOnce(true).setOngoing(pct<100).setContentIntent(pi).addAction(new Notification.Action.Builder(null,"STOP",sp).build()).build();}
 public android.os.IBinder onBind(Intent i){return null;}
 public void onDestroy(){stop.set(true);super.onDestroy();}
}
