package com.ramaj.wtsappcleaner;

import android.content.*;import android.database.*;import android.database.sqlite.*;import java.util.*;

public class DatabaseHelper extends SQLiteOpenHelper {
    static final int V=1; public DatabaseHelper(Context c){super(c,"ramaj_cleaner.db",null,V);}
    public void onCreate(SQLiteDatabase d){d.execSQL("CREATE TABLE files(path TEXT PRIMARY KEY,size INTEGER,mtime INTEGER,category TEXT,sent INTEGER,quick TEXT,full TEXT,phash INTEGER,width INTEGER,height INTEGER,duration INTEGER,v1 INTEGER,v2 INTEGER,v3 INTEGER,lastSeen INTEGER)");d.execSQL("CREATE INDEX idx_files_size ON files(size)");d.execSQL("CREATE TABLE dups(id INTEGER PRIMARY KEY AUTOINCREMENT,keepPath TEXT,dupPath TEXT UNIQUE,kind TEXT,confidence INTEGER,category TEXT,bytes INTEGER,moved INTEGER DEFAULT 0,created INTEGER)");d.execSQL("CREATE INDEX idx_dups_created ON dups(created DESC)");d.execSQL("CREATE TABLE moves(id INTEGER PRIMARY KEY AUTOINCREMENT,originalPath TEXT,newPath TEXT,kind TEXT,bytes INTEGER,created INTEGER,restored INTEGER DEFAULT 0)");}
    public void onUpgrade(SQLiteDatabase d,int a,int b){}
    void upsert(Models.FileEntry f,long run){ContentValues v=new ContentValues();v.put("path",f.path);v.put("size",f.size);v.put("mtime",f.mtime);v.put("category",f.category);v.put("sent",f.sent?1:0);v.put("lastSeen",run);SQLiteDatabase d=getWritableDatabase();Cursor c=d.rawQuery("SELECT size,mtime FROM files WHERE path=?",new String[]{f.path});boolean same=false;if(c.moveToFirst())same=c.getLong(0)==f.size&&c.getLong(1)==f.mtime;c.close();if(same){d.update("files",v,"path=?",new String[]{f.path});}else{v.putNull("quick");v.putNull("full");v.putNull("phash");v.putNull("duration");v.putNull("v1");v.putNull("v2");v.putNull("v3");d.insertWithOnConflict("files",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}
    String getString(String path,String col){Cursor c=getReadableDatabase().query("files",new String[]{col},"path=?",new String[]{path},null,null,null);String s=null;if(c.moveToFirst()&&!c.isNull(0))s=c.getString(0);c.close();return s;}
    Long getLong(String path,String col){Cursor c=getReadableDatabase().query("files",new String[]{col},"path=?",new String[]{path},null,null,null);Long x=null;if(c.moveToFirst()&&!c.isNull(0))x=c.getLong(0);c.close();return x;}
    void putString(String path,String col,String val){ContentValues v=new ContentValues();v.put(col,val);getWritableDatabase().update("files",v,"path=?",new String[]{path});}
    void putImage(String path,long ph,int w,int h){ContentValues v=new ContentValues();v.put("phash",ph);v.put("width",w);v.put("height",h);getWritableDatabase().update("files",v,"path=?",new String[]{path});}
    void putVideo(String path,Models.VideoSig s){ContentValues v=new ContentValues();v.put("duration",s.duration);v.put("width",s.width);v.put("height",s.height);v.put("v1",s.h1);v.put("v2",s.h2);v.put("v3",s.h3);getWritableDatabase().update("files",v,"path=?",new String[]{path});}
    boolean hasDup(String dupPath){Cursor c=getReadableDatabase().rawQuery("SELECT 1 FROM dups WHERE dupPath=? LIMIT 1",new String[]{dupPath});boolean b=c.moveToFirst();c.close();return b;}
    long addDup(String keep,String dup,String kind,int conf,String cat,long bytes){ContentValues v=new ContentValues();v.put("keepPath",keep);v.put("dupPath",dup);v.put("kind",kind);v.put("confidence",conf);v.put("category",cat);v.put("bytes",bytes);v.put("created",System.currentTimeMillis());return getWritableDatabase().insertWithOnConflict("dups",null,v,SQLiteDatabase.CONFLICT_IGNORE);}
    void markMoved(String dupPath){ContentValues v=new ContentValues();v.put("moved",1);getWritableDatabase().update("dups",v,"dupPath=?",new String[]{dupPath});}
    void addMove(String old,String n,String kind,long bytes){ContentValues v=new ContentValues();v.put("originalPath",old);v.put("newPath",n);v.put("kind",kind);v.put("bytes",bytes);v.put("created",System.currentTimeMillis());getWritableDatabase().insert("moves",null,v);}
    List<Models.Dup> recentDups(String filter,int limit){ArrayList<Models.Dup> out=new ArrayList<>();String where=null,args[]=null;if(filter!=null&&!filter.equals("ALL")){where="kind=?";args=new String[]{filter};}Cursor c=getReadableDatabase().query("dups",null,where,args,null,null,"created DESC",String.valueOf(limit));while(c.moveToNext()){Models.Dup x=new Models.Dup();x.id=c.getLong(c.getColumnIndexOrThrow("id"));x.keepPath=c.getString(c.getColumnIndexOrThrow("keepPath"));x.dupPath=c.getString(c.getColumnIndexOrThrow("dupPath"));x.kind=c.getString(c.getColumnIndexOrThrow("kind"));x.confidence=c.getInt(c.getColumnIndexOrThrow("confidence"));x.category=c.getString(c.getColumnIndexOrThrow("category"));x.bytes=c.getLong(c.getColumnIndexOrThrow("bytes"));x.moved=c.getInt(c.getColumnIndexOrThrow("moved"))==1;out.add(x);}c.close();return out;}
    long countKind(String kind){Cursor c=getReadableDatabase().rawQuery("SELECT count(*) FROM dups WHERE kind=?",new String[]{kind});long v=c.moveToFirst()?c.getLong(0):0;c.close();return v;}
    long movedBytes(){Cursor c=getReadableDatabase().rawQuery("SELECT coalesce(sum(bytes),0) FROM moves WHERE restored=0",null);long v=c.moveToFirst()?c.getLong(0):0;c.close();return v;}
    List<String[]> moves(int limit){ArrayList<String[]> o=new ArrayList<>();Cursor c=getReadableDatabase().rawQuery("SELECT id,originalPath,newPath,kind,bytes,restored FROM moves ORDER BY created DESC LIMIT "+limit,null);while(c.moveToNext())o.add(new String[]{c.getString(0),c.getString(1),c.getString(2),c.getString(3),c.getString(4),c.getString(5)});c.close();return o;}
    void markRestored(long id){ContentValues v=new ContentValues();v.put("restored",1);getWritableDatabase().update("moves",v,"id=?",new String[]{String.valueOf(id)});}
}
