package com.ramaj.wtsappcleaner;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;

public class MainActivity extends Activity {
 private final int BG=Color.rgb(7,17,15),SURF=Color.rgb(14,28,25),TEXT=Color.rgb(243,255,249),MUTED=Color.rgb(147,170,161),GREEN=Color.rgb(41,230,165),PURPLE=Color.rgb(124,92,255),YELLOW=Color.rgb(255,191,74),RED=Color.rgb(255,91,110);
 private FrameLayout body;private RingProgressView ring;private TextView phase,detail,scanCount,exactCount,visualCount,spaceCount;private MiniBarChartView chart;private DatabaseHelper db;private BroadcastReceiver recv;private String resultFilter="ALL";
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);db=new DatabaseHelper(this);setContentView(buildShell());showDashboard();requestNeeded();recv=new BroadcastReceiver(){public void onReceive(Context c,Intent i){updateFromIntent(i);}};}
 @Override protected void onStart(){super.onStart();registerReceiver(recv,new IntentFilter(CleanerService.BROADCAST),RECEIVER_NOT_EXPORTED);refreshDashboardFromPrefs();}
 @Override protected void onStop(){try{unregisterReceiver(recv);}catch(Exception ignored){}super.onStop();}
 private View buildShell(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);
  LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.VERTICAL);top.setPadding(Ui.dp(this,20),Ui.dp(this,18),Ui.dp(this,20),Ui.dp(this,14));GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{Color.rgb(9,37,31),Color.rgb(28,18,55)});g.setCornerRadii(new float[]{0,0,0,0,Ui.dp(this,28),Ui.dp(this,28),Ui.dp(this,28),Ui.dp(this,28)});top.setBackground(g);TextView title=Ui.text(this,"Ramaj Wtsapp Cleaner",25,TEXT,true);TextView sub=Ui.text(this,"Smart duplicate intelligence • 100% on-device",12,MUTED,false);top.addView(title);top.addView(sub);root.addView(top,new LinearLayout.LayoutParams(-1,Ui.dp(this,82)));
  body=new FrameLayout(this);root.addView(body,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout nav=new LinearLayout(this);nav.setPadding(Ui.dp(this,8),Ui.dp(this,6),Ui.dp(this,8),Ui.dp(this,8));nav.setGravity(Gravity.CENTER);String[] ns={"⌂\nDashboard","◎\nDuplicates","↶\nHistory","⚙\nSettings"};for(int i=0;i<4;i++){Button x=new Button(this);x.setAllCaps(false);x.setText(ns[i]);x.setTextSize(11);x.setTextColor(i==0?GREEN:MUTED);x.setBackgroundColor(Color.TRANSPARENT);final int k=i;x.setOnClickListener(v->{if(k==0)showDashboard();else if(k==1)showResults();else if(k==2)showHistory();else showSettings();});nav.addView(x,new LinearLayout.LayoutParams(0,Ui.dp(this,58),1));}root.addView(nav,new LinearLayout.LayoutParams(-1,Ui.dp(this,70)));return root;}
 private ScrollView scroll(){ScrollView s=new ScrollView(this);s.setFillViewport(true);return s;}
 private LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(Ui.dp(this,16),Ui.dp(this,14),Ui.dp(this,16),Ui.dp(this,24));return l;}
 private void setBody(View v){body.removeAllViews();body.addView(v,new FrameLayout.LayoutParams(-1,-1));}
 private void showDashboard(){ScrollView s=scroll();LinearLayout c=column();s.addView(c);LinearLayout hero=Ui.card(this);FrameLayout hf=new FrameLayout(this);ring=new RingProgressView(this);hf.addView(ring,new FrameLayout.LayoutParams(Ui.dp(this,205),Ui.dp(this,205),Gravity.CENTER));hero.addView(hf,new LinearLayout.LayoutParams(-1,Ui.dp(this,220)));phase=Ui.text(this,"Ready for a smart scan",18,TEXT,true);phase.setGravity(Gravity.CENTER);detail=Ui.text(this,"Exact SHA-256 + real image pHash + video frame matching",12,MUTED,false);detail.setGravity(Gravity.CENTER);hero.addView(phase);hero.addView(detail);c.addView(hero);c.addView(Ui.space(this,12));
  LinearLayout row=new LinearLayout(this);scanCount=stat(row,"Files scanned","0",GREEN);exactCount=stat(row,"Exact","0",GREEN);c.addView(row,new LinearLayout.LayoutParams(-1,Ui.dp(this,92)));LinearLayout row2=new LinearLayout(this);visualCount=stat(row2,"Visual matches","0",PURPLE);spaceCount=stat(row2,"Recovered","0 B",YELLOW);c.addView(row2,new LinearLayout.LayoutParams(-1,Ui.dp(this,92)));c.addView(Ui.space(this,10));
  LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);Button smart=Ui.button(this,"⚡ Smart Scan",Color.rgb(24,154,111));Button deep=Ui.button(this,"🧠 Deep Visual",Color.rgb(92,67,194));actions.addView(smart,new LinearLayout.LayoutParams(0,Ui.dp(this,54),1));Space sp=new Space(this);actions.addView(sp,new LinearLayout.LayoutParams(Ui.dp(this,8),1));actions.addView(deep,new LinearLayout.LayoutParams(0,Ui.dp(this,54),1));smart.setOnClickListener(v->startScan(false));deep.setOnClickListener(v->startScan(true));c.addView(actions);Button stop=Ui.button(this,"■ Stop safely",Color.rgb(88,42,48));stop.setOnClickListener(v->stopService(new Intent(this,CleanerService.class)));c.addView(Ui.space(this,8));c.addView(stop,new LinearLayout.LayoutParams(-1,Ui.dp(this,48)));
  c.addView(Ui.space(this,14));LinearLayout ca=Ui.card(this);TextView ct=Ui.text(this,"Duplicate intelligence",16,TEXT,true);ca.addView(ct);chart=new MiniBarChartView(this);ca.addView(chart,new LinearLayout.LayoutParams(-1,Ui.dp(this,150)));c.addView(ca);setBody(s);refreshDashboardFromPrefs();}
 private TextView stat(LinearLayout row,String label,String val,int color){LinearLayout card=Ui.card(this);TextView v=Ui.text(this,val,22,color,true),l=Ui.text(this,label,11,MUTED,false);card.addView(v);card.addView(l);row.addView(card,new LinearLayout.LayoutParams(0,-1,1));Space s=new Space(this);row.addView(s,new LinearLayout.LayoutParams(Ui.dp(this,8),1));return v;}
 private void startScan(boolean deep){if(!hasStorage()){requestNeeded();Toast.makeText(this,"Allow All files access, then tap scan again",Toast.LENGTH_LONG).show();return;}Intent i=new Intent(this,CleanerService.class).setAction(CleanerService.ACT_START).putExtra("deep",deep);startForegroundService(i);}
 private boolean hasStorage(){return Build.VERSION.SDK_INT<30||Environment.isExternalStorageManager();}
 private void requestNeeded(){if(Build.VERSION.SDK_INT>=30&&!Environment.isExternalStorageManager()){try{startActivity(new Intent(Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION, Uri.parse("package:"+getPackageName())));}catch(Exception e){startActivity(new Intent(Settings.ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION));}}if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS,Manifest.permission.READ_MEDIA_IMAGES,Manifest.permission.READ_MEDIA_VIDEO,Manifest.permission.READ_MEDIA_AUDIO},9);}
 private void updateFromIntent(Intent i){if(ring==null)return;int p=i.getIntExtra("percent",0);String ph=i.getStringExtra("phase"),de=i.getStringExtra("detail");long cur=i.getLongExtra("current",0),tot=i.getLongExtra("total",0),ex=i.getLongExtra("exact",0),vi=i.getLongExtra("visual",0),po=i.getLongExtra("possible",0),rec=i.getLongExtra("recovered",0);ring.setProgress(p,ph);phase.setText(ph);detail.setText(de);scanCount.setText(cur+(tot>0?" / "+tot:""));exactCount.setText(String.valueOf(ex));visualCount.setText(String.valueOf(vi+po));spaceCount.setText(Ui.bytes(rec));chart.setValues(ex,vi,po,db.recentDups("ALL",500).stream().filter(x->x.moved).count());}
 private void refreshDashboardFromPrefs(){if(ring==null)return;android.content.SharedPreferences p=getSharedPreferences("live",0);int pc=p.getInt("percent",0);String ph=p.getString("phase","Ready"),de=p.getString("detail","Exact SHA-256 + real visual matching");ring.setProgress(pc,ph);phase.setText(ph);detail.setText(de);scanCount.setText(p.getLong("current",0)+(p.getLong("total",0)>0?" / "+p.getLong("total",0):""));long ex=db.countKind("EXACT"),vi=db.countKind("VISUAL"),po=db.countKind("POSSIBLE");exactCount.setText(String.valueOf(ex));visualCount.setText(String.valueOf(vi+po));spaceCount.setText(Ui.bytes(db.movedBytes()));chart.setValues(ex,vi,po,db.recentDups("ALL",500).stream().filter(x->x.moved).count());}

 private void showResults(){LinearLayout all=new LinearLayout(this);all.setOrientation(LinearLayout.VERTICAL);all.setPadding(Ui.dp(this,14),Ui.dp(this,12),Ui.dp(this,14),0);TextView h=Ui.text(this,"Duplicate Review",22,TEXT,true);all.addView(h);TextView sub=Ui.text(this,"Exact = mathematically confirmed • Visual = pixel/frame similarity",12,MUTED,false);all.addView(sub);LinearLayout filters=new LinearLayout(this);String[] fs={"ALL","EXACT","VISUAL","POSSIBLE"};for(String f:fs){Button b=Ui.button(this,f.equals("ALL")?"All":f.equals("EXACT")?"Confirmed":f.equals("VISUAL")?"Visual":"Possible",f.equals(resultFilter)?Color.rgb(24,154,111):Color.rgb(24,45,40));b.setOnClickListener(v->{resultFilter=f;showResults();});filters.addView(b,new LinearLayout.LayoutParams(0,Ui.dp(this,42),1));}all.addView(Ui.space(this,10));all.addView(filters);ListView list=new ListView(this);list.setDividerHeight(Ui.dp(this,8));list.setDivider(null);list.setAdapter(new DupAdapter(db.recentDups(resultFilter,150)));all.addView(list,new LinearLayout.LayoutParams(-1,0,1));setBody(all);}
 private class DupAdapter extends BaseAdapter{final List<Models.Dup> a;DupAdapter(List<Models.Dup>x){a=x;}public int getCount(){return a.size();}public Object getItem(int p){return a.get(p);}public long getItemId(int p){return a.get(p).id;}public View getView(int p,View cv,android.view.ViewGroup parent){Models.Dup d=a.get(p);LinearLayout card=Ui.card(MainActivity.this);TextView k=Ui.text(MainActivity.this,(d.kind.equals("EXACT")?"✅ CONFIRMED":"VISUAL".equals(d.kind)?"👁 VISUAL MATCH":"🟡 POSSIBLE")+"   "+d.confidence+"%",13,d.kind.equals("EXACT")?GREEN:d.kind.equals("VISUAL")?PURPLE:YELLOW,true);card.addView(k);card.addView(Ui.text(MainActivity.this,new File(d.dupPath).getName(),15,TEXT,true));card.addView(Ui.text(MainActivity.this,d.category+" • can save "+Ui.bytes(d.bytes),11,MUTED,false));card.addView(Ui.text(MainActivity.this,"Keep: "+new File(d.keepPath).getName(),10,MUTED,false));if(!d.moved&&!d.kind.equals("EXACT")){Button m=Ui.button(MainActivity.this,"Move this duplicate safely",Color.rgb(24,154,111));m.setOnClickListener(v->{new Thread(()->{try{File x=MoveManager.move(MainActivity.this,d.dupPath,d.category,d.kind);db.markMoved(d.dupPath);db.addMove(d.dupPath,x.getAbsolutePath(),d.kind,d.bytes);runOnUiThread(()->showResults());}catch(Exception e){runOnUiThread(()->Toast.makeText(MainActivity.this,e.getMessage(),Toast.LENGTH_LONG).show());}}).start();});card.addView(m,new LinearLayout.LayoutParams(-1,Ui.dp(MainActivity.this,42)));}else if(d.moved)card.addView(Ui.text(MainActivity.this,"Moved safely ✓",11,GREEN,true));return card;}}

 private void showHistory(){LinearLayout all=column();all.addView(Ui.text(this,"Move History & Restore",22,TEXT,true));all.addView(Ui.text(this,"Nothing is permanently deleted by the cleaner.",12,MUTED,false));all.addView(Ui.space(this,10));for(String[] x:db.moves(100)){LinearLayout c=Ui.card(this);c.addView(Ui.text(this,new File(x[2]).getName(),14,TEXT,true));c.addView(Ui.text(this,x[3]+" • "+Ui.bytes(Long.parseLong(x[4])),11,MUTED,false));if("0".equals(x[5])){Button r=Ui.button(this,"↶ Restore original",Color.rgb(40,72,65));r.setOnClickListener(v->new Thread(()->{try{MoveManager.restore(x[2],x[1]);db.markRestored(Long.parseLong(x[0]));runOnUiThread(this::showHistory);}catch(Exception e){runOnUiThread(()->Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show());}}).start());c.addView(r,new LinearLayout.LayoutParams(-1,Ui.dp(this,40)));}else c.addView(Ui.text(this,"Restored ✓",11,GREEN,true));all.addView(c);all.addView(Ui.space(this,8));}ScrollView s=scroll();s.addView(all);setBody(s);}
 private void showSettings(){ScrollView s=scroll();LinearLayout c=column();s.addView(c);c.addView(Ui.text(this,"Cleaner Settings",22,TEXT,true));c.addView(Ui.text(this,"Accuracy first. Nothing visual is auto-moved unless you review it.",12,MUTED,false));android.content.SharedPreferences p=getSharedPreferences("settings",0);c.addView(toggle("Auto-move SHA-256 confirmed duplicates","Only 100% exact copies",p,"autoExact",true));c.addView(toggle("Include Sent folders","Find copies inside WhatsApp/Sent",p,"sent",true));c.addView(toggle("Scan WhatsApp Business","Include Business media roots",p,"business",true));c.addView(Ui.space(this,12));LinearLayout sen=Ui.card(this);sen.addView(Ui.text(this,"Visual sensitivity",15,TEXT,true));TextView val=Ui.text(this,"Balanced",12,GREEN,true);sen.addView(val);SeekBar sb=new SeekBar(this);sb.setMax(2);sb.setProgress(p.getInt("sensitivity",1));sb.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar b,int x,boolean u){val.setText(x==0?"Strict":x==1?"Balanced":"Aggressive");p.edit().putInt("sensitivity",x).apply();}public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}});sen.addView(sb);c.addView(sen);c.addView(Ui.space(this,10));LinearLayout dst=Ui.card(this);File rr=MoveManager.removableRoot(this);dst.addView(Ui.text(this,"Safe destination",15,TEXT,true));dst.addView(Ui.text(this,(rr==null?"Fallback storage":rr.getAbsolutePath())+"/what's app duplicate files",11,MUTED,false));c.addView(dst);c.addView(Ui.space(this,10));LinearLayout pr=Ui.card(this);pr.addView(Ui.text(this,"🔒 Privacy",15,GREEN,true));pr.addView(Ui.text(this,"All hashes, image pixels and video frames are processed locally on your phone. No upload, no account, no cloud.",12,MUTED,false));c.addView(pr);setBody(s);}
 private View toggle(String title,String sub,android.content.SharedPreferences p,String key,boolean def){LinearLayout c=Ui.card(this);LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.addView(Ui.text(this,title,14,TEXT,true));tx.addView(Ui.text(this,sub,11,MUTED,false));Switch sw=new Switch(this);sw.setChecked(p.getBoolean(key,def));sw.setOnCheckedChangeListener((b,v)->p.edit().putBoolean(key,v).apply());r.addView(tx,new LinearLayout.LayoutParams(0,-2,1));r.addView(sw);c.addView(r);c.setPadding(Ui.dp(this,14),Ui.dp(this,10),Ui.dp(this,14),Ui.dp(this,10));return c;}
}
