package com.ramaj.wtsappcleaner;
import android.content.*;import android.os.*;import java.io.*;import java.util.*;

final class MoveManager {
 static File removableRoot(Context c){File[] dirs=c.getExternalFilesDirs(null);if(dirs!=null)for(File d:dirs){if(d==null)continue;String p=d.getAbsolutePath();if(!p.startsWith("/storage/emulated/")){int i=p.indexOf("/Android/data/");if(i>0)return new File(p.substring(0,i));}}File st=new File("/storage");File[] a=st.listFiles();if(a!=null)for(File f:a)if(f.isDirectory()&&f.getName().contains("-"))return f;return null;}
 static File destination(Context c,String cat,String kind){File root=removableRoot(c);if(root==null)root=c.getExternalFilesDir(null);File base=new File(root,"what's app duplicate files/"+cat);if(!"EXACT".equals(kind)){String sub="VISUAL".equals(kind)?"Visual Match":"POSSIBLE".equals(kind)?"Possible":"High Confidence";base=new File(base,"_Review/"+sub);}base.mkdirs();return base;}
 static File move(Context c,String path,String cat,String kind)throws IOException{File src=new File(path);if(!src.isFile())throw new FileNotFoundException(path);File dir=destination(c,cat,kind);if(!dir.exists()&&!dir.mkdirs())throw new IOException("Destination not writable: "+dir);File dst=unique(dir,src.getName());if(!src.renameTo(dst)){try(InputStream in=new BufferedInputStream(new FileInputStream(src),1024*1024);OutputStream out=new BufferedOutputStream(new FileOutputStream(dst),1024*1024)){byte[] b=new byte[1024*1024];int n;while((n=in.read(b))>0)out.write(b,0,n);}if(!src.delete()){dst.delete();throw new IOException("Could not remove source");}}return dst;}
 static void restore(String from,String to)throws IOException{File src=new File(from),dst=new File(to);if(!src.exists())throw new FileNotFoundException(from);File p=dst.getParentFile();if(p!=null)p.mkdirs();if(dst.exists())dst=unique(p,dst.getName());if(!src.renameTo(dst)){try(InputStream in=new FileInputStream(src);OutputStream out=new FileOutputStream(dst)){byte[] b=new byte[1024*1024];int n;while((n=in.read(b))>0)out.write(b,0,n);}if(!src.delete())throw new IOException("Restore cleanup failed");}}
 static File unique(File dir,String name){File d=new File(dir,name);if(!d.exists())return d;String base=name,ext="";int dot=name.lastIndexOf('.');if(dot>0){base=name.substring(0,dot);ext=name.substring(dot);}for(int i=1;;i++){d=new File(dir,base+" ("+i+")"+ext);if(!d.exists())return d;}}
}
